vich_uploader:
    db_driver: orm

    mappings:
        work_image:
            uri_prefix: img/portfolio
            upload_destination: '%kernel.project_dir%/public/img/portfolio'

        article_image:
            uri_prefix: img/blog
            upload_destination: '%kernel.project_dir%/public/img/blog'


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
